// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWg_StY_FBdfq8OYJt-rrojWpBSMgI93k',
    appId: '1:745497194359:web:d36ef258f119bbfeb1bb72',
    messagingSenderId: '745497194359',
    projectId: 'smart-transport-aca3b',
    authDomain: 'smart-transport-aca3b.firebaseapp.com',
    storageBucket: 'smart-transport-aca3b.firebasestorage.app',
    measurementId: 'G-P5XWX74T9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkCkil_zeP9ViiYsxs-R9Jvh2zKraW9rA',
    appId: '1:745497194359:android:ca07e44b41995ec0b1bb72',
    messagingSenderId: '745497194359',
    projectId: 'smart-transport-aca3b',
    storageBucket: 'smart-transport-aca3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYXQ9aLsRYE7d0HdMwtxeYEgX0n1Cpdoo',
    appId: '1:745497194359:ios:5a0a4b08c86a9edbb1bb72',
    messagingSenderId: '745497194359',
    projectId: 'smart-transport-aca3b',
    storageBucket: 'smart-transport-aca3b.firebasestorage.app',
    iosBundleId: 'com.example.smartTrans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYXQ9aLsRYE7d0HdMwtxeYEgX0n1Cpdoo',
    appId: '1:745497194359:ios:5a0a4b08c86a9edbb1bb72',
    messagingSenderId: '745497194359',
    projectId: 'smart-transport-aca3b',
    storageBucket: 'smart-transport-aca3b.firebasestorage.app',
    iosBundleId: 'com.example.smartTrans',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWg_StY_FBdfq8OYJt-rrojWpBSMgI93k',
    appId: '1:745497194359:web:a45bcf5dfbff2f8ab1bb72',
    messagingSenderId: '745497194359',
    projectId: 'smart-transport-aca3b',
    authDomain: 'smart-transport-aca3b.firebaseapp.com',
    storageBucket: 'smart-transport-aca3b.firebasestorage.app',
    measurementId: 'G-LHSP27B0L3',
  );
}
